#cloud-config
# vim: syntax=yaml
#
# This is the configuration syntax that the write_files module
# will know how to understand. encoding can be given b64 or gzip or (gz+b64).
# The content will be decoded accordingly and then written to the path that is
# provided. 
#
# Note: Content strings here are truncated for example purposes.
# Run yum upgrade
#package_upgrade: true

final_message: "The EHOS vm is up after $UPTIME seconds"

# Create custom condor configuration file to create an execute node
write_files:
-   content: |
      ##  What machine is your central manager?
      CONDOR_HOST = {master_ip}
      use ROLE: Execute

      SEC_PASSWORD_FILE = /etc/condor/passwords.d/POOL
      SEC_DAEMON_AUTHENTICATION = REQUIRED
      SEC_DAEMON_INTEGRITY = REQUIRED
      SEC_DAEMON_AUTHENTICATION_METHODS = PASSWORD
      SEC_NEGOTIATOR_AUTHENTICATION = REQUIRED
      SEC_NEGOTIATOR_INTEGRITY = REQUIRED
      SEC_NEGOTIATOR_AUTHENTICATION_METHODS = PASSWORD
      SEC_CLIENT_AUTHENTICATION_METHODS = FS, PASSWORD, KERBEROS, GSI
      ALLOW_DAEMON = condor_pool@*/*, condor@*/$(IP_ADDRESS)
      ALLOW_NEGOTIATOR = condor_pool@*/{master_ip}
    owner: root:root
    path: /etc/condor/config.d/00personal_condor.config
    permissions: '0644'

runcmd:
  - yum install -y epel-release

  # htcondor install and setup
  - wget -P /tmp/ http://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor
  - rpm --import /tmp/RPM-GPG-KEY-HTCondor
  - wget -P /etc/yum.repos.d https://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-stable-rhel7.repo
  - yum -y install condor
  - mkdir /etc/condor/passwords.d
  - chown 700 /etc/condor/passwords.d
  - condor_store_cred add -cp {password}

  # Start condor and enable it on start
  - systemctl enable condor
  - systemctl start condor

