#cloud-config
# This does not work right now, I will look at it later as it is the nicer way of doing this
#
# Run yum upgrade
package_upgrade: true

yum_repos:
    # The name of the repository
    docker:
        # Any repository configuration options
        # See: man yum.conf
        #
        # This one is required!
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        enabled: true
        gpgcheck: false
    htcondor:
        baseurl: https://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-stable-rhel7.repo
        enabled: true
        gpgcheck: true
        gpgkey: http://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor


groups:
  - docker


packages:  
  ## some editors
  - vim
  - nano
  ## dependencies
  - python-pip
  - squashfs-tools
  - wget 
  - python-devel
  - libarchive-devel
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  - docker-ce
  - autofs
  # ideally this should be python 3.6 not 3.4!
  - python34
  - python34-pip
  - condor.x86_64


runcmd:
  - yum -y groupinstall "development tools"

  ## Enable condor to run docker
  - usermod -aG docker condor

  ## Enable rootless use of docker
  - usermod -aG docker centos

  ## Start autofs and enable automatic start at boot
  - service autofs start
  - systemctl enable autofs

  ## Start docker and enable automatic start at boot
  - service docker start
  - systemctl enable docker

# Start condor and enable it on start
  - service condor start
  - systemctl enable condor
  
final_message: "The EHOS base system is up after $UPTIME seconds"
