#cloud-config
# vim: syntax=yaml
#
# Run yum upgrade
package_upgrade: true

groups:
  - ehos

users:
  - name: ehos
    primary_group: ehos
    system: true
    lock_passwd: false

# Create custom condor configuration file to create an execute node
write_files:
{write_files}

runcmd:
- pip install htcondor
- pip install python-openstackclient
- pip install git+https://github.com/elixir-no-nels/ehos-python.git
  #- ehos_setup.sh /usr/local/etc/ehos_master.yaml


