#cloud-config
# vim: syntax=yaml
#
# Run yum upgrade
package_upgrade: true

groups:
  - ehos

users:
  - name: ehos
    primary_group: ehos
    system: true
    lock_passwd: false

# Create custom condor configuration file to create an execute node
write_files:
{write_files}

runcmd:
  - pip install htcondor
  - pip install openstacksdk
  - pip install python-openstackclient
  - pip3 install --prefix /usr/local/ git+https://github.com/elixir-no-nels/ehos-python.git
  #- ehos_setup.sh /usr/local/etc/ehos_master.yaml

final_message: "The EHOS master is up after $UPTIME seconds"


